//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedGameOptions.localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedGameOptions.localize.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic roads are available from the start.
        /// </summary>
        internal static string BasicRoads {
            get {
                return ResourceManager.GetString("BasicRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulldozing structures built recently gives full refund.
        /// </summary>
        internal static string BulldozingStructures {
            get {
                return ResourceManager.GetString("BulldozingStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        internal static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable achievements.
        /// </summary>
        internal static string EnableAchievements {
            get {
                return ResourceManager.GetString("EnableAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable random disasters for scenarios.
        /// </summary>
        internal static string EnableDisasters {
            get {
                return ResourceManager.GetString("EnableDisasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info View buttons are always enabled.
        /// </summary>
        internal static string InfoViewBtnsEnabled {
            get {
                return ResourceManager.GetString("InfoViewBtnsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial money (set blank to not change). Example: 70 000.
        /// </summary>
        internal static string InitialMoney {
            get {
                return ResourceManager.GetString("InitialMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro tunnels can be constructed without a metro station.
        /// </summary>
        internal static string MetroTunnels {
            get {
                return ResourceManager.GetString("MetroTunnels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of small useful features..
        /// </summary>
        internal static string ModDesc {
            get {
                return ResourceManager.GetString("ModDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Game Options.
        /// </summary>
        internal static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set number of purchasable areas (uncheck this if using 81 tiles mod).
        /// </summary>
        internal static string NumberAreas {
            get {
                return ResourceManager.GetString("NumberAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil depletion rate.
        /// </summary>
        internal static string OilDepletionRate {
            get {
                return ResourceManager.GetString("OilDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore depletion rate.
        /// </summary>
        internal static string OreDepletionRate {
            get {
                return ResourceManager.GetString("OreDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources depletion rate.
        /// </summary>
        internal static string ResourcesDepletionRate {
            get {
                return ResourceManager.GetString("ResourcesDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      (select Megalopolis to unlock all).
        /// </summary>
        internal static string SelectMegalopolis {
            get {
                return ResourceManager.GetString("SelectMegalopolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train tracks can be constructed without a train station.
        /// </summary>
        internal static string TrainTracks {
            get {
                return ResourceManager.GetString("TrainTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchanged.
        /// </summary>
        internal static string Unchanged {
            get {
                return ResourceManager.GetString("Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlimited.
        /// </summary>
        internal static string unlimited {
            get {
                return ResourceManager.GetString("unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocks (requires game reload).
        /// </summary>
        internal static string UnlocksTitle {
            get {
                return ResourceManager.GetString("UnlocksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock everything up to the following milestone.
        /// </summary>
        internal static string UnlockUpTo {
            get {
                return ResourceManager.GetString("UnlockUpTo", resourceCulture);
            }
        }
    }
}
