//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedGameOptions.localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedGameOptions.localize.ja", typeof(ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エリア.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎道路が最初から有効.
        /// </summary>
        internal static string BasicRoads {
            get {
                return ResourceManager.GetString("BasicRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近建設した建物を壊すと、100%の資金が戻ってくる.
        /// </summary>
        internal static string BulldozingStructures {
            get {
                return ResourceManager.GetString("BulldozingStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経済.
        /// </summary>
        internal static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実績がいつも有効.
        /// </summary>
        internal static string EnableAchievements {
            get {
                return ResourceManager.GetString("EnableAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダムな災害がシナリオでも起きる.
        /// </summary>
        internal static string EnableDisasters {
            get {
                return ResourceManager.GetString("EnableDisasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報ビューボタンはいつも有効.
        /// </summary>
        internal static string InfoViewBtnsEnabled {
            get {
                return ResourceManager.GetString("InfoViewBtnsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム開始時の資金（空に設定すると、変更なし）。例：70,000.
        /// </summary>
        internal static string InitialMoney {
            get {
                return ResourceManager.GetString("InitialMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地下鉄駅がなくても地下鉄の線路を建設できる.
        /// </summary>
        internal static string MetroTunnels {
            get {
                return ResourceManager.GetString("MetroTunnels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小さくて便利なオプションが集まっているMOD.
        /// </summary>
        internal static string ModDesc {
            get {
                return ResourceManager.GetString("ModDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拡張オプション.
        /// </summary>
        internal static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入できるエリアの数（81 tiles mod使用の場合は未チェック）.
        /// </summary>
        internal static string NumberAreas {
            get {
                return ResourceManager.GetString("NumberAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 石油の枯渇率.
        /// </summary>
        internal static string OilDepletionRate {
            get {
                return ResourceManager.GetString("OilDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鉱石の枯渇率.
        /// </summary>
        internal static string OreDepletionRate {
            get {
                return ResourceManager.GetString("OreDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資源の枯渇.
        /// </summary>
        internal static string ResourcesDepletionRate {
            get {
                return ResourceManager.GetString("ResourcesDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      （全てをアンロックするにはMegalopolisを選択する）.
        /// </summary>
        internal static string SelectMegalopolis {
            get {
                return ResourceManager.GetString("SelectMegalopolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鉄道駅がなくても鉄道の線路を建設できる.
        /// </summary>
        internal static string TrainTracks {
            get {
                return ResourceManager.GetString("TrainTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更なし.
        /// </summary>
        internal static string Unchanged {
            get {
                return ResourceManager.GetString("Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無限.
        /// </summary>
        internal static string unlimited {
            get {
                return ResourceManager.GetString("unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アンロック（ゲームリスタートが必要）.
        /// </summary>
        internal static string UnlocksTitle {
            get {
                return ResourceManager.GetString("UnlocksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次のマイルストーンまでアンロック.
        /// </summary>
        internal static string UnlockUpTo {
            get {
                return ResourceManager.GetString("UnlockUpTo", resourceCulture);
            }
        }
    }
}
