//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedGameOptions.localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtendedGameOptions.localize.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Области.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные дороги доступны с самого начала.
        /// </summary>
        internal static string BasicRoads {
            get {
                return ResourceManager.GetString("BasicRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снос недавно построенных зданий возвращает полную стоимость.
        /// </summary>
        internal static string BulldozingStructures {
            get {
                return ResourceManager.GetString("BulldozingStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экономика.
        /// </summary>
        internal static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получать достижения даже при включенных модификациях.
        /// </summary>
        internal static string EnableAchievements {
            get {
                return ResourceManager.GetString("EnableAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайные катастрофы в сценариях.
        /// </summary>
        internal static string EnableDisasters {
            get {
                return ResourceManager.GetString("EnableDisasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все информационные обзоры всегда доступны.
        /// </summary>
        internal static string InfoViewBtnsEnabled {
            get {
                return ResourceManager.GetString("InfoViewBtnsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальный капитал (пусто, если изменять не нужно). Пример: 70 000.
        /// </summary>
        internal static string InitialMoney {
            get {
                return ResourceManager.GetString("InitialMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно строить туннели метро без станции метро.
        /// </summary>
        internal static string MetroTunnels {
            get {
                return ResourceManager.GetString("MetroTunnels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маленькие полезные настройки собранные в одном месте..
        /// </summary>
        internal static string ModDesc {
            get {
                return ResourceManager.GetString("ModDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширенные настройки.
        /// </summary>
        internal static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные области (убрать галочку, если используется 81 tiles mod).
        /// </summary>
        internal static string NumberAreas {
            get {
                return ResourceManager.GetString("NumberAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нефть.
        /// </summary>
        internal static string OilDepletionRate {
            get {
                return ResourceManager.GetString("OilDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руда.
        /// </summary>
        internal static string OreDepletionRate {
            get {
                return ResourceManager.GetString("OreDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость истощения ресурсов.
        /// </summary>
        internal static string ResourcesDepletionRate {
            get {
                return ResourceManager.GetString("ResourcesDepletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      (выбрать Megalopolis чтобы разблокировать всё).
        /// </summary>
        internal static string SelectMegalopolis {
            get {
                return ResourceManager.GetString("SelectMegalopolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно строить железную дорогу без ж.д. станции.
        /// </summary>
        internal static string TrainTracks {
            get {
                return ResourceManager.GetString("TrainTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без изменений.
        /// </summary>
        internal static string Unchanged {
            get {
                return ResourceManager.GetString("Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неограниченно.
        /// </summary>
        internal static string unlimited {
            get {
                return ResourceManager.GetString("unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать контент (необходима перезагрузка игры).
        /// </summary>
        internal static string UnlocksTitle {
            get {
                return ResourceManager.GetString("UnlocksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать до этапа.
        /// </summary>
        internal static string UnlockUpTo {
            get {
                return ResourceManager.GetString("UnlockUpTo", resourceCulture);
            }
        }
    }
}
